version: '3.8'
services:
  webappmr:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
    # Uncomment if you need to persist data or mount volumes
    # volumes:
    #   - ./WebAppMR/appsettings.Development.json:/app/appsettings.Development.json
    #   - ./WebAppMR/appsettings.json:/app/appsettings.json
